name: Windows .exe

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - name: Build
      run: dotnet publish -c Release
    - name: Artifact Upload
      uses: actions/upload-artifact@v2
      with:
        name: 'OcuSwap.exe'
        path: OcuSwap/bin/Release/netcoreapp3.1/win-x64/publish/*
